# Generated by Django 4.2 on 2023-04-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profile-pic/uploads/%y/%m/%d'),
        ),
    ]
