# Generated by Django 4.2 on 2023-04-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cadetlogbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadetlogbook',
            name='work_status',
            field=models.BooleanField(default=False),
        ),
    ]
