# Generated by Django 4.2 on 2023-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cadetlogbook_work_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadetlogbook',
            name='work_summary',
        ),
        migrations.AddField(
            model_name='cadetlogbook',
            name='work_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
