# Generated by Django 4.2 on 2023-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cadetlogbook_work_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadetlogbook',
            name='start_and_end_date',
        ),
        migrations.AddField(
            model_name='cadetlogbook',
            name='department',
            field=models.CharField(choices=[('biology', 'Biology'), ('chemistry', 'Chemistry')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cadetlogbook',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
