# Generated by Django 4.2 on 2023-04-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cadetlogbook_start_and_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadetlogbook',
            name='comment',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='cadetlogbook',
            name='department',
            field=models.CharField(choices=[('biology', 'Biology'), ('chemistry', 'Chemistry'), ('computer science', 'Computer Science')], max_length=50, null=True),
        ),
    ]
