# Generated by Django 4.2 on 2023-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cadetlogbook_comment_alter_cadetlogbook_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadetlogbook',
            name='work_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=200),
        ),
    ]
