# Generated by Django 4.2 on 2023-04-17 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_cadetlogbook_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadetlogbook',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_cadetlogbook', to=settings.AUTH_USER_MODEL),
        ),
    ]
